name: Ejemplo CI/CD 

on: [push]

jobs:
    inicio:
      runs-on: windows-latest
      #Pasos:
      steps:
        - name: texto
          run: echo "Pasos para clonar repositorios a github actions"
        - name: Checkout
          uses: actions/checkout@v4.2.2
    bluid:
      runs-on: windows-latest
      needs: [inicio]
      steps:
        - name: texto
          run: echo "Counstruir"
        - name: installar PHP y composer
          run: |
            choco install php --version=8.1
            choco install composer
            php -v
            composer --version
        - name: Installar MySql
          run: |
            choco install mysql 
            Start-Service mysql
      runs-on: windows-latest
      needs: [bluid]
      steps:
        - name: test
          run: echo "Test"

    deploy:
      runs-on: windows-latest
      needs: [test]
      steps:
        - name: deploy
          run: echo "Deploy"
            
          