name: Ejemplo CI/CD 

on: [push]

jobs:
    inicio:
      runs-on: windows-latest
      #Pasos:
      steps:
        - name: mostrar texto
          run: echo "Hola mundo"
    bluid:
      runs-on: windows-latest
      needs: [inicio]
      steps:
        - name: texto
          run: echo "Counstruir"
        - name: installar PHP y composer
          run: |
            choco install php --version=8.1
            choco install composer
            php -v
            composer --version
    test:
      runs-on: windows-latest
      needs: [bluid]
      steps:
        - name: test
          run: echo "Test"

    deploy:
      runs-on: windows-latest
      needs: [test]
      steps:
        - name: deploy
          run: echo "Deploy"
            
          