name: Ejemplo CI/CD 

on: [push]

jobs:
    inicio:
      runs-on: windows-latest
      #Pasos:
      steps:
        - name: mostrar texto
          run: echo "Hola mundo"
    bluid:
      runs-on: windows-latest
      needs: [inicio]
      steps:
        - name: texto
          run: echo "Counstruir"
    test:
      runs-on: windows-latest
      needs: [bluid]
      steps:
        - name: test
          run: echo "Test"
            
          