name: Ejemplo CI/CD 

on: [push]

jobs:
    inicio:
      runs-on: windows-latest
      #Pasos:
      steps:
        - name: texto
          run: echo "Pasos para clonar repositorios a github actions"
        - name: Checkout
          uses: actions/checkout@v4.2.2
    bluid:
      runs-on: windows-latest
      needs: [inicio]
      steps:
        - name: texto
          run: echo "Counstruir"
        - name: installar PHP y composer
          run: |
            choco install php --version=8.1
            choco install composer
            php -v
            composer --version
        - name: Instalar Mysql
          run: |
            choco install mysql --version=8.0.27 -y
            Start-Service mysql
            mysql -u root -e "ALTER USER 'root'@'localhost'IDENTIFIED WITH mysql_native_password BY 'root';" mysql -u root -proot -e "CREATE DATABASE lumen_db;"
    test:
      runs-on: windows-latest
      needs: [bluid]
      steps:
        - name: test
          run: echo "Test"

    deploy:
      runs-on: windows-latest
      needs: [test]
      steps:
        - name: deploy
          run: echo "Deploy"
            
          