name: Ejemplo CI/CD 

on: [push]

jobs:
    inicio:
      runs-on: windows-latest
      #Pasos:
      steps:
        - name: mostrar texto
          run: echo "Hola mundo"
        
            
           